title: IaC Lab
tagline: A brand new course on Learning Lab
description: >-
  A quick way to learn Infrastructure Automation using Azure Resource Manager
  Template.
template:
  repo: iac-lab-template
  name: iac-lab
before:
  - type: createIssue
    title: Welcome!
    body: new-issue.md
steps:
  - title: First step
    description: The first step in your course
    event: issues.assigned
    link: '{{ repoUrl }}'
    actions:
      - type: closeIssue
